--[[
  idempotentEnqueue.lua
  Atomically enqueue a job only if the idempotency key does not already exist.

  KEYS[1] = idempotency key  (e.g. "idempotency:<userKey>")
  KEYS[2] = waiting list key (e.g. "queue:main_queue:waiting:normal")
  ARGV[1] = jobId            (new UUID generated by the caller)
  ARGV[2] = ttlSeconds       (24 * 3600 = 86400)

  Returns:
    - The jobId that "owns" this idempotency slot.
      • If the slot was NEWLY claimed   → returns ARGV[1] (we enqueued)
      • If the slot already existed     → returns the previously stored jobId (we skipped)

  Why Lua?
  --------
  A plain application-level check (GET → branch → SET + LPUSH) has a
  TOCTOU race: two producers can both GET, both see nil, and both enqueue.
  Lua scripts execute atomically on the Redis server — no other command
  can interleave between the SET NX and the LPUSH.
--]]

local idempotencyKey = KEYS[1]
local waitingListKey = KEYS[2]
local jobId          = ARGV[1]
local ttl            = tonumber(ARGV[2])

-- Attempt to claim the idempotency slot (SET NX EX).
-- Returns OK on success, nil if the key already exists.
local claimed = redis.call('SET', idempotencyKey, jobId, 'NX', 'EX', ttl)

if claimed then
  -- First time this idempotency key is seen — push job to the waiting list.
  redis.call('LPUSH', waitingListKey, jobId)
  return jobId
else
  -- Already processed — return the existing jobId without re-enqueuing.
  return redis.call('GET', idempotencyKey)
end
